#PyTorch Gradient descent

using Auto Gradient function

In [14]:
import torch

In [15]:
"""
Function:- 2x^4 + x^3 + 3x^2 + 5x + 1

Derivative:- 8x^3 + 3x^2 + 6x + 5

calculate gradient of Function

"""

'\nFunction:- 2x^4 + x^3 + 3x^2 + 5x + 1\n\nDerivative:- 8x^3 + 3x^2 + 6x + 5\n\ncalculate gradient of Function\n\n'

In [16]:
x= torch.tensor(2.0,requires_grad=True)
x

# Thise Sets up computational tracking on the tensor.
# So now PyTorch can keep an eye on this tensor throughout
# the computational graph.
# It's notm just floating around as a separate variable.


tensor(2., requires_grad=True)

In [17]:
# Define function

y= 2*x**4 + x**3 + 3*x**2 + 5*x + 1
y

# This is the value of y when x=2

tensor(63., grad_fn=<AddBackward0>)

In [18]:
type(y)

torch.Tensor

In [23]:
y.backward()

# This is going to perform the backpropagation


In [26]:
x.grad

# torch(93.)
# 93 is the representation of if you were to plug in
# the X value into the 1st derivative of Y
# with respect to X.
# So 93 is gonna be the slope of the polynomial
# at that point where X=2.

# This is the slope of the polynomial at the point (2,63)



tensor(93.)

#Back -  Propagation on multiple steps

 Now let's do something more complex, involving layers y and z between x and out out layer out

In [27]:
x= torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [28]:
# Create 1st layer

y = 3*x +2
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [29]:
z = 2*y**2
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [31]:
out =  z.mean()
out

tensor(140., grad_fn=<MeanBackward0>)

In [33]:
# Perform back propagation to find the gradient of X
# with respect to this output layer

out.backward()

In [34]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])