# PyTorch  Tensor Operation Part - 1

In [2]:
import torch
import numpy as np

In [3]:
"""
Indexing and Slicing

"""

'\nIndexing and Slicing\n\n'

In [4]:
x=torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
x[1][1]

tensor(3)

In [6]:
type(x[1][1])

torch.Tensor

In [8]:
x[:,1]

tensor([1, 3, 5])

In [9]:
x[:,1:] #to print column as column

tensor([[1],
        [3],
        [5]])

In [11]:
x=torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x=x.reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x =  torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.shape

torch.Size([10])

In [19]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
z= x.view(2,5)
z
# view reflect most current data
# z in not linked with x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[0]=9999
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [25]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [26]:
x =  torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x.shape

torch.Size([10])

In [28]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
# if we change size from 10 to 11 then x.view(2,-1)
# will show error
# Runtime error:- shape '[2,-1]' is invalid for input of size 11
# because 11 is not evenly divisible by 2


In [31]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Tensor Arithmetic

In [32]:
a = torch.tensor([1.,2.,3.])
a

tensor([1., 2., 3.])

In [33]:
b= torch.tensor([4.,5.,6.])
b

tensor([4., 5., 6.])

In [34]:
a+b

tensor([5., 7., 9.])

In [37]:
torch.add(a,b)

tensor([5., 7., 9.])

In [38]:
#a = a + b

a.mul(b)

tensor([ 4., 10., 18.])

In [39]:
a

tensor([1., 2., 3.])

In [40]:
a=a.mul(b)
a

tensor([ 4., 10., 18.])

In [41]:
a = a. mul_(b)
a

tensor([ 16.,  50., 108.])

# PyTorch  Tensor Operation Part - 2

In [42]:
a = torch.tensor([1.,2.,3.])
a

tensor([1., 2., 3.])

In [43]:
b= torch.tensor([4.,5.,6.])
b

tensor([4., 5., 6.])

In [45]:
a * b # element wise operation

tensor([ 4., 10., 18.])

In [46]:
# this is not true way of matrix multiplication
# one way is dot product
# other is true 2D multiplication(shape should be same of 2
# matrix)


In [47]:
# dot product
a.dot(b)

tensor(32.)

In [49]:
a=torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [50]:
b=torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [51]:
a.shape

torch.Size([2, 3])

In [52]:
b.shape

torch.Size([3, 2])

In [53]:
# no of columns in a matches with no of rows in b

In [56]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [57]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [ ]:
# L2 Ecludiean norm

In [61]:
 x = torch.tensor([2.,3.,4.,5.])
 x

tensor([2., 3., 4., 5.])

In [59]:
x.norm()

tensor(7.3485)

In [60]:
x.numel()

4

In [62]:
len(x)

4

In [63]:
a=torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [65]:
len(a)

2

In [66]:
a.numel()

6