In [389]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [390]:
print(torch.__version__)

2.6.0+cu124


#PyTorch Tensors


**Creating Tensor**

In [391]:
# Scalar Tensor

# 0D tensor

# https://docs.pytorch.org/docs/stable/tensors.html

# torch.tensor is a multi-dimensional matrix containing
# elements of a single data type.


In [392]:
 scalar=torch.tensor(7)
 scalar

tensor(7)

In [393]:
scalar.ndim

0

In [394]:
# Get tensor back as Python integer

scalar.item()

7

In [395]:
 # Vector

 # 1D tensor

vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [396]:
vector.ndim

1

In [397]:
vector.shape

torch.Size([3])

In [398]:
# Matrix

# 2D tensor

matrix=torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [399]:
matrix.ndim

2

In [400]:
matrix.shape

torch.Size([2, 2])

In [401]:
matrix[0]

tensor([1, 2])

In [402]:
matrix[1]

tensor([3, 4])

In [403]:
# Tensor

ten=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [404]:
ten.ndim

3

In [405]:
ten.shape

torch.Size([1, 3, 3])

In [406]:
ten[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Creating Random Tensor

In [407]:
# Why random tensor

# Random tensors are important because the way
# many neural netowkrs learn is that they start with
# tensors full of random numbers and then adjust
# those random numbers to better represent the data.

# Start with random number -> look at data-> update
# random numbers -> look at data -> update random numbers




In [408]:
# create a random tensor of size (3,4)
# Uniform random tensor
# torch.rand()

# Values are sampled from a uniform distribution between
# 0(inclusive) and 1 (exclusive)

# [0,1)

# shape:- 3 rows , 4 columns


In [409]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5220, 0.2842, 0.9012, 0.7001],
        [0.7839, 0.5053, 0.2463, 0.6272],
        [0.7441, 0.7764, 0.9120, 0.0059]])

In [410]:
random_tensor.ndim

2

In [411]:
random_tensor.shape

torch.Size([3, 4])

In [412]:
random_tensor[0]

tensor([0.5220, 0.2842, 0.9012, 0.7001])

In [413]:
random_tensor[1]

tensor([0.7839, 0.5053, 0.2463, 0.6272])

In [414]:
random_tensor[2]

tensor([0.7441, 0.7764, 0.9120, 0.0059])

In [415]:
# create a random tensor with similar
# shape to an  image tensor

# 3 channels(R,G,B), height,width
image_tensor=torch.rand(size=(3,224,224))
image_tensor.shape,image_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [416]:
# Normal(Gaussian) Distribution

# torch.randn()

# Values are drawn from a standard normal distribution
# mean=0 & std=1

# Useful for intializing weights in Neural Network.



In [417]:
ten_normal=torch.randn(3,4)
ten_normal

tensor([[-0.3920, -0.1585,  0.4863,  1.5767],
        [ 0.8346,  0.2247,  0.6837,  0.0360],
        [ 1.2871,  0.8616, -0.3382,  1.2065]])

In [418]:
ten_normal.ndim


2

In [419]:
ten_normal.shape

torch.Size([3, 4])

In [420]:
ten_normal[0]

tensor([-0.3920, -0.1585,  0.4863,  1.5767])

In [421]:
ten_normal[1]

tensor([0.8346, 0.2247, 0.6837, 0.0360])

In [422]:
ten_normal[2]

tensor([ 1.2871,  0.8616, -0.3382,  1.2065])

In [423]:
# Random Integers

# torch.randint()

# Returns a tensor of random integers in the range
# ([low,high]) with shape(2,4)


In [424]:
random_tensor=torch.randint(0,10,(2,4))
random_tensor

tensor([[2, 2, 6, 5],
        [3, 1, 1, 5]])

In [425]:
random_tensor.ndim


2

In [426]:
random_tensor.shape

torch.Size([2, 4])

In [427]:
random_tensor[0]

tensor([2, 2, 6, 5])

In [428]:
random_tensor[1]

tensor([3, 1, 1, 5])

In [429]:
# Random Binary Tensor(Bernoulli Distribution)

# torch.bernoulli()

# Return a 0 or 1 based on the given probabilities

In [430]:
probs = torch.tensor([[0.1, 0.8], [0.7, 0.3]])
tensor = torch.bernoulli(probs)
print(tensor)

tensor([[0., 1.],
        [1., 1.]])


In [431]:
# Set  Random seed for Reproducibility

torch.manual_seed(32)

random_tensor=torch.randint(0,10,(2,3))
random_tensor

tensor([[5, 3, 3],
        [4, 4, 6]])

# Creating Tensors with Zeros and Ones


In [432]:
#rows,columns

zero_tensor=torch.zeros(2,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [433]:
zero_tensor.dtype


torch.float32

In [434]:
one_tensor=torch.ones(2,3,dtype=torch.int32)
one_tensor

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [435]:
one_tensor.dtype

torch.int32

In [436]:
# set up a data type

one_data_type=torch.ones(size=(3,4),dtype=torch.int32)
one_data_type

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

# Creating a Tensor Range and Tensors like other Tensors

In [437]:
# Use torch.arange()

# will include 1st value and exclude last value

one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [438]:
# Values from 0 to 100 with step 5

# it will include 0 and exclude 100

tensors = torch.arange(start=0,end=100,step=5)
tensors

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [439]:
# creating a tensors "Like" another tensor

x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [440]:
# torch.zeros_like(x)

zero_like=torch.zeros_like(x)
zero_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [441]:
zero_like.dtype

torch.int64

In [442]:
# torch.ones_like(x)

one_like=torch.ones_like(x)
one_like

tensor([[1, 1, 1],
        [1, 1, 1]])

In [443]:
one_like.dtype

torch.int64

In [444]:
# torch.rand_like

torch.manual_seed(32)

random_like=torch.rand_like(x,dtype=torch.float)
random_like

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793]])

# Dealing with Tensor Data Types

In [445]:
# float 32 tensor

float_32= torch.tensor([1.0,2.0,3.0],dtype=None)
float_32

tensor([1., 2., 3.])

In [446]:
float_32.dtype

# default data type in PyTorch in float 32

torch.float32

In [447]:
# dtype:- What Data Type is tensor(e.g: float32,int64)

# device:- What devide is your tensor on

# require_grad:- Whether or not to track gradients with
# tensor operations

# most important parameters while creating tensors



In [448]:
"""
Note:- Tensor DataType is one of the 3 big errors you'll
run into with PyTorch and Deep Learning

1.) Tensors not right datatype

2.) Tensors not right shape

3.) Tensors not the right device

"""

"\nNote:- Tensor DataType is one of the 3 big errors you'll\nrun into with PyTorch and Deep Learning\n\n1.) Tensors not right datatype\n\n2.) Tensors not right shape\n\n3.) Tensors not the right device\n\n"

In [449]:
float_32= torch.tensor([1.0,2.0,3.0],dtype=None,
                       device="cpu",
                       requires_grad=True)
float_32

tensor([1., 2., 3.], requires_grad=True)

In [450]:
float_16= float_32.type(torch.float16)
float_16

tensor([1., 2., 3.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

In [451]:
float_16.dtype

torch.float16

In [452]:
x = torch.tensor([1, 2, 3])
print(x.device)  # cpu

# Move to GPU
if torch.cuda.is_available():
    x = x.to("cuda")
    print(x.device)  # cuda:0


cpu


In [453]:
float_32

tensor([1., 2., 3.], requires_grad=True)

In [454]:
float_16

tensor([1., 2., 3.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

In [455]:
float_16*float_32

tensor([1., 4., 9.], grad_fn=<MulBackward0>)

In [456]:
(float_16*float_32).dtype

torch.float32

In [457]:
int_32=torch.tensor([2,3,4],dtype=torch.int32)
int_32

tensor([2, 3, 4], dtype=torch.int32)

In [458]:
int_32*float_32

tensor([ 2.,  6., 12.], grad_fn=<MulBackward0>)

In [459]:
(int_32*float_32).dtype

torch.float32

In [460]:
# Getting information from tensors

# 1.) Tensors not right datatype
# To do get datatype from a tensor, can use tensor.dtype

# 2.) Tensors not right shape
# to get shape from a tensor, can use tensor.shape

# 3.) Tensors not on the right device
# to get device from a tensor, can use tensor.device


In [461]:
# create a tensor

new_tensor=torch.rand(3,4)
new_tensor

tensor([[0.6481, 0.0229, 0.5874, 0.3254],
        [0.9485, 0.5219, 0.8782, 0.7254],
        [0.6929, 0.0259, 0.9319, 0.0913]])

In [462]:
new_tensor.dtype

torch.float32

In [463]:
new_tensor.shape

torch.Size([3, 4])

In [464]:
new_tensor.size() # size is a function and shape
# is attribute

# () at the end meaning its a method


torch.Size([3, 4])

In [465]:
new_tensor.device

device(type='cpu')

In [466]:
# What is precision in computing?

# In computer science, the precision of a numerical
# quantity is a measure of the detail in which
# the quantity is expressed. This is usually
# measured in bits, but sometimes in decimal
# digits. It is related to precision in
# mathematics, which describes the number of
# digits that are used to express a value.


# Tensor Operations

In [467]:
# Tensor Operations


# 1.) Addition

# 2.) Subtraction

# 3.) Multiplication (Element wise)

# 4.) Division

# 5.) Matrix Multiplication


In [468]:
# create a tensor


tensor= torch.tensor([1,2,3])

new_tensor=tensor + 10
new_tensor



tensor([11, 12, 13])

In [469]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [470]:
mul_tensor= tensor*10
mul_tensor

tensor([10, 20, 30])

In [471]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [472]:
sub_tensor = tensor-1
sub_tensor

tensor([0, 1, 2])

In [473]:
torch.sub(tensor,1)

tensor([0, 1, 2])

In [474]:
tensor

tensor([1, 2, 3])

In [475]:
d_tensor=torch.tensor([10,20,30])

div_tensor=d_tensor/10
div_tensor

tensor([1., 2., 3.])

In [476]:
torch.div(d_tensor,10)

tensor([1., 2., 3.])

# Matrix Multiplication

In [477]:
# Two main ways of perfoming multiplication in
# Neural Network and Deep Learning

# 1.) Element vise Multiplication

# 2.) Matrix Multiplication - Dot Product

# There are two main rules that perfoming matrix
# Multiplication needs to satisfy:

# 1.) The **inner dimension must match

# (3,2) * (3,2) will not work
# (2,3) * (3,2) will work
# (3,2) * (2,3) will work

# 2.) The resulting matrix has the shape of the
# ** Outer dimension

# (2,3) * (3,2) = (2,2)
# (3,2) * (2,3) = (3,3)




In [478]:
# 1.) Element vise Mulitplication

tensor= torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [479]:
tensor*tensor

tensor([1, 4, 9])

In [480]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [481]:
# [1,2,3] * [1,2,3] = [1*1 + 2*2 + 3*3]=1+4+9=14

In [482]:
# One of the most common errors in deep learning
# is Shape errors



In [483]:
tensor_A =torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [484]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [485]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [486]:
"""
torch.matmul(tensor_A,tensor_B)

RuntimeError         Traceback (most recent call last)
/tmp/ipython-input-1993702425.py in <cell line: 0>()
----> 1 torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be
multiplied (3x2 and 3x2)
"""

'\ntorch.matmul(tensor_A,tensor_B)\n\nRuntimeError         Traceback (most recent call last)\n/tmp/ipython-input-1993702425.py in <cell line: 0>()\n----> 1 torch.matmul(tensor_A,tensor_B)\n\nRuntimeError: mat1 and mat2 shapes cannot be\nmultiplied (3x2 and 3x2)\n'

In [487]:
# To fix tensor shape issue, we can manipulate shape
# of one of our tensors using matrix transpose

# A Transpose switches the axes or dimensions of a
# given tensor.



In [488]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [489]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [490]:
tensor_B.shape,tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [491]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [492]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [493]:
# Matrix Multiplication using "@"

t_A=torch.tensor([[1,2],
                [3,4]])
print(t_A)

print("\n")

print(t_A.shape)

tensor([[1, 2],
        [3, 4]])


torch.Size([2, 2])


In [494]:

t_B=torch.tensor([[1,2,3],
                [4,5,6]])
print(t_B)

print("\n")

print(t_B.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])


In [495]:
C = t_A @ t_B
C

tensor([[ 9, 12, 15],
        [19, 26, 33]])

In [496]:
# torch.mm()

# Only for 2D tensors

torch.mm(t_A,t_B)


tensor([[ 9, 12, 15],
        [19, 26, 33]])

In [497]:

# torch.bmm() - Batch Matrix Multiplication
# 3D tensors only

A = torch.randn(1, 3, 4)
B = torch.randn(1, 4, 5)

print(A)

print("\n")

print(B)

print("\n")

C = torch.bmm(A, B)         # Result: (1, 3, 5)
print(C)


tensor([[[-0.1453, -2.6965,  0.8150, -0.3143],
         [-0.7490, -0.7898,  0.1287,  0.4246],
         [-0.0974,  1.2594, -1.2466, -0.0168]]])


tensor([[[ 1.0564, -0.4243, -0.2669,  0.2851,  2.0572],
         [-0.3627,  0.0671,  0.1321, -0.6149,  1.3700],
         [ 1.2196,  0.6020,  1.0561,  0.5673, -1.3971],
         [ 1.0257,  2.3957,  0.5670, -0.2198, -0.1880]]])


tensor([[[ 1.4960, -0.3816,  0.3652,  2.1480, -5.0726],
         [ 0.0876,  1.3594,  0.4722,  0.2517, -2.8824],
         [-2.0971, -0.6648, -1.1337, -1.5057,  3.2697]]])


# Finding the Min, Max, and Sum of Tensors (Tensor Aggregation)

In [498]:
# creat a tensor

x= torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [499]:
# Find the min

torch.min(x), x.min()

(tensor(1), tensor(1))

In [500]:
torch.min(x,dim=0) # Colum wise minimum value

torch.return_types.min(
values=tensor([1, 2]),
indices=tensor([0, 0]))

In [501]:
torch.min(x,dim=1) # Row wise minimum value

torch.return_types.min(
values=tensor([1, 3]),
indices=tensor([0, 0]))

In [502]:
# Find the max

torch.max(x),x.max()

(tensor(4), tensor(4))

In [503]:
torch.max(x,dim=0) # Colum wise maximum value

torch.return_types.max(
values=tensor([3, 4]),
indices=tensor([1, 1]))

In [504]:
torch.max(x,dim=1) # Row wise maximum value

torch.return_types.max(
values=tensor([2, 4]),
indices=tensor([1, 1]))

In [505]:
# Find the mean

# torch.mean(x),x.mean()

# RuntimeError: mean(): could not infer output dtype.
# Input dtype must be either
# a floating point or complex dtype. Got: Long

In [506]:
# to find mean tensor's data type must be float

torch.mean(x.float()), x.float().mean()

(tensor(2.5000), tensor(2.5000))

In [507]:
# other way to convert into float data type

torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(2.5000), tensor(2.5000))

In [508]:
torch.mean(x.float(),dim=0) # Column wise mean

tensor([2., 3.])

In [509]:
torch.mean(x.float(),dim=1) # Row wise mean

tensor([1.5000, 3.5000])

In [510]:
# Find the sum

torch.sum(x),x.sum()

(tensor(10), tensor(10))

In [511]:
torch.sum(x,dim=0) # Column wise sum

tensor([4, 6])

In [512]:
torch.sum(x,dim=1) # Row wise sum

tensor([3, 7])

# Find the Positional Max and Min of Tensors

In [513]:
x= torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [514]:
# Find the position in tensor that has the minimum
# value with argmin()- returns the index position
# of target tensor where minimum value occurs

x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [515]:
# Find the position in tensor that has the maximum
# value with argmax()

torch.argmax(x),x.argmax()

(tensor(3), tensor(3))

# Other Tensor Aggregation function

In [516]:
# Product of all elements

x=torch.tensor([[1,2],[3,4]])

torch.prod(x) # 1*2*3*4=24

tensor(24)

In [517]:
# standard deviation

x = torch.tensor([1,2,3,4])

torch.std(x.float())


tensor(1.2910)

In [518]:
# variance

x = torch.tensor([1,2,3,4])

torch.var(x.float())

tensor(1.6667)

In [519]:
# Cumulative sum
# dim=0 is must parameter
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])

torch.cumsum(x,dim=0)


tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [520]:
# Cumulative product

# dim=0 is must parameter

x = torch.tensor([1,2,3,4,5])

torch.cumprod(x,dim=0)

tensor([  1,   2,   6,  24, 120])

In [521]:
# Meadian and Mode

x = torch.tensor([1,2,3,3,4])

print("Median Value of x: -",torch.median(x))

print("\n")

print("Mode of x :- ",torch.mode(x))

Median Value of x: - tensor(3)


Mode of x :-  torch.return_types.mode(
values=tensor(3),
indices=tensor(3))


In [522]:
# keepdim parameter

# Whether to retain reduced dimension as size 1
# for example:- [2,1] instead of [2,]

x = torch.tensor([[1,2],[3,4]])
print(x)

print("\n")

total_column_wise=torch.sum(x,dim=0,keepdim=True)

print("total_column_wise :- ",total_column_wise)

print("\n")

total_row_wise=torch.sum(x,dim=1,keepdim=True)

print("total_row_wise :-",total_row_wise)

tensor([[1, 2],
        [3, 4]])


total_column_wise :-  tensor([[4, 6]])


total_row_wise :- tensor([[3],
        [7]])


# Reshaping, Viewing and Stacking Tensors

In [523]:
# Reshaping :- Reshapes an input tensor to a defined
# shape

# View :- Return a view of an input tensor of certain
# shape but keep the same memory as the original tensor

# Stacking :- Combine multiple tensor on top of each
# other.




In [524]:
# Create a tensor

import torch

x = torch.arange(1.,10.)
print(x)
print("\n")
print(x.shape)


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


torch.Size([9])


In [525]:
# Add an extra dimension
# when we change the shape of the tensor
# the new shape must be compatible with the existing
# tensor


# reshape_x=x.reshape(1,7)
# reshape_x,reshape_x.shape

# Add an extra dimension
"""
----> 3 reshape_x=x.reshape(1,7)
      4 reshape_x,reshape_x.shape

RuntimeError: shape '[1, 7]' is invalid
for input of size 9"""

"\n----> 3 reshape_x=x.reshape(1,7)\n      4 reshape_x,reshape_x.shape\n\nRuntimeError: shape '[1, 7]' is invalid\nfor input of size 9"

In [526]:
# 1 extra dimension will be added outside

reshape_x=x.reshape(1,9)
reshape_x,reshape_x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [527]:
reshape_x=x.reshape(3,3)
reshape_x,reshape_x.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [528]:
# 1 extra dimentions will be added inside
reshape_x=x.reshape(9,1)
reshape_x,reshape_x.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [529]:
# it will work with (1,9)/(9,1)

# other combinations will give an error

# as long as the given dimension can reshape it
# evenly it will work

In [530]:
# Change the view

z = x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [531]:
# changing z changes x because view of a tensor
# share the same memory as the original tensor

z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [532]:
# Stack tensors on top of each other


x = torch.arange(1.,5.)

x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [533]:
y_stack = torch.stack([x,x,x,x],dim=1)
y_stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])

# Other Functions

In [534]:
# flatten() - Collaps dimenstions into 1
# combine values in one 1 dimension

x = torch.tensor([[1,2],[3,4]])
print(x.flatten())

print(x.view(x.size(0),-1))

#flatten everything except batch



tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])


# Squeezing, Unsquezeeing and Permuting Tensors

In [535]:

# Squeeze :- Removes all 'single' dimenstions from a
# tensor

# Unsqueeze :- Add a '1' dimension to a target tensor

# Permute :-  Reorder dimensions
# Changes the order of axes(dimenstions) of a tensor


In [536]:
x = torch.arange(1.,10.)
print(x)

print("\n")

x=x.reshape(1,9)
print("New tensor:- ",x)

print("\n")

print(x.reshape(1,9).shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


New tensor:-  tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


torch.Size([1, 9])


In [537]:
# will remove 1 dimension
# in simple term it will remove one square bracket

x_squeeze=x.squeeze()
x_squeeze

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [538]:
x_squeeze.shape

torch.Size([9])

In [539]:
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [540]:
x = torch.arange(1.,10.)
print(x)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [541]:
x_unsqueeze= x.unsqueeze(0)
x_unsqueeze

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [542]:
x_unsqueeze.shape

torch.Size([1, 9])

In [543]:
x_unsqueeze= x.unsqueeze(1)
x_unsqueeze

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [544]:
x_unsqueeze.shape

torch.Size([9, 1])

In [545]:
# permuting a tensor

torch.manual_seed(32)

x = torch.rand(size=(2,2,3))
# height,width,colour_channels
x

tensor([[[0.8757, 0.2721, 0.4141],
         [0.7857, 0.1130, 0.5793]],

        [[0.6481, 0.0229, 0.5874],
         [0.3254, 0.9485, 0.5219]]])

In [546]:
x.shape

torch.Size([2, 2, 3])

In [547]:
 # Permute the original tensor to rearragne the axis
 # or dim order

x_permute=x.permute(2,0,1)
x_permute.shape

torch.Size([3, 2, 2])

In [548]:
x_permute

tensor([[[0.8757, 0.7857],
         [0.6481, 0.3254]],

        [[0.2721, 0.1130],
         [0.0229, 0.9485]],

        [[0.4141, 0.5793],
         [0.5874, 0.5219]]])

# Selecting Data From Tensors(Indexing)

In [549]:
# Select data from tensor using index

# Indexing the PyTorch is similar to indexing with
# NumPy



In [550]:
# create a tensor

x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [551]:
x = x.reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [552]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [553]:
x[0][0] # dim=1


tensor([1, 2, 3])

In [554]:
x[0][0][0] # last dimension

tensor(1)

In [555]:
# x[1][1][1]

# IndexError: index 1 is out of bounds for
# dimension 0 with size 1


In [556]:
x[0][1][1]

tensor(5)

In [557]:
x[0][2][2]

tensor(9)

In [558]:
# use ":" to select all targe dimensions

x[:,0]

tensor([[1, 2, 3]])

In [559]:
# all values of 0th and 1st dimension but only
# index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [560]:
# get all values of the 0 dimension but only
# 1 index value of 1st and 2nd dimension


x[:,1,1]

tensor([5])

In [561]:
x[0,1,1]

tensor(5)

In [562]:
# get index 0 of 0th dimension. and 1st dimension and
# all value of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])

In [563]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [564]:
x[0,2,2]

tensor(9)

In [565]:
x[0,2,:]

tensor([7, 8, 9])

# PyTorch Tensors and NumPy

In [566]:
#  Numpy is a popular scientific Python Numerical
# computing library

# And because of this , PyTorch has functionality
# to interact with it.

# Data in NumPy , want in PyTorch tensor
# torch.from_numpy(ndarray)

# from PyTorch to NumPy
# torch.Tensor.numpy()

In [567]:
import torch
import numpy as np

In [568]:
arr = np.arange(1.0,8.0)
arr, arr.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

In [569]:
tensor=torch.from_numpy(arr)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [570]:
# change the value of an array, let's see how it
# affects our tensor

arr= arr+1
arr,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [571]:
# it will not change the value of a tensor

In [572]:
# tensor to numpy

tensor=torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [573]:
tensor.dtype

torch.float32

In [574]:
numpy_tensor=tensor.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [575]:
# change the tensor, let's see what happens
# to numpy array

tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# PyTorch Reproducability (Taking the Random out of Random)

In [576]:
# Ensuring Reproducability in PyTorch means making sure
# our results stay the same every time we run the code,
# even if it uses randomness
# e.g:- weight initialization, shuffling data, dropout


In [577]:
# In short how Neural Network learns :-

# start with random numbers -> tensor opersations->
# update random numbers to try and make them better
# representations of the data -> repeat the process

# To reduce the randomness in neural network and
# PyTorch comes the concept of a "random seed"




In [578]:
# create a tensor

import torch

random_tensor_A =  torch.rand(3,4)
random_tensor_B =  torch.rand(3,4)

print(random_tensor_A)
print("\n")
print(random_tensor_B)
print("\n")
print(random_tensor_A==random_tensor_B)


tensor([[0.8782, 0.7254, 0.6929, 0.0259],
        [0.9319, 0.0913, 0.7177, 0.7271],
        [0.4967, 0.9308, 0.3677, 0.2049]])


tensor([[0.6646, 0.3886, 0.0787, 0.1447],
        [0.1809, 0.6440, 0.1504, 0.7280],
        [0.8867, 0.2971, 0.7828, 0.5105]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [579]:
# let's create random but reproducible tensors

import torch
import random
import numpy as np

# set the random seed
seed=18

torch.manual_seed(seed)

random.seed(seed)
np.random.seed(seed)

random_tensor_C =  torch.rand(3,4)
random_tensor_D =  torch.rand(3,4)

print(random_tensor_C)
print("\n")
print(random_tensor_D)
print("\n")
print(random_tensor_C==random_tensor_D)

tensor([[0.4958, 0.4588, 0.3961, 0.7521],
        [0.9220, 0.6045, 0.5511, 0.5441],
        [0.1717, 0.2169, 0.0349, 0.9457]])


tensor([[0.5220, 0.2842, 0.9012, 0.7001],
        [0.7839, 0.5053, 0.2463, 0.6272],
        [0.7441, 0.7764, 0.9120, 0.0059]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [580]:
# setup seed each time before creating a tensor

torch.manual_seed(seed)
random_tensor_C =  torch.rand(3,4)

torch.manual_seed(seed)
random_tensor_D =  torch.rand(3,4)

print(random_tensor_C)
print("\n")
print(random_tensor_D)
print("\n")
print(random_tensor_C==random_tensor_D)

tensor([[0.4958, 0.4588, 0.3961, 0.7521],
        [0.9220, 0.6045, 0.5511, 0.5441],
        [0.1717, 0.2169, 0.0349, 0.9457]])


tensor([[0.4958, 0.4588, 0.3961, 0.7521],
        [0.9220, 0.6045, 0.5511, 0.5441],
        [0.1717, 0.2169, 0.0349, 0.9457]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Different Ways of Accessing a GPU in PyTorch

In [581]:
# Running tensors and PyTorch objects on the GPUs
# makes faster computations



In [582]:
# Getting GPU

# Use Google Colab for free GPU
# Buy your own GPU
# Use cloud AWS,Azure,GCP


In [583]:
"""
import torch

print(torch.cuda.is_available()) # True if GPU is available

print("\n")

print(torch.cuda.device_count()) # Number of GPUs

print("\n")

print(torch.cuda.get_device_name(0)) # Name of the first GPU
"""

'\nimport torch\n\nprint(torch.cuda.is_available()) # True if GPU is available\n\nprint("\n")\n\nprint(torch.cuda.device_count()) # Number of GPUs\n\nprint("\n")\n\nprint(torch.cuda.get_device_name(0)) # Name of the first GPU\n'

In [584]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [585]:
# Setup device agnostic code


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device


device(type='cpu')

# Setting up Device - Agnostic code and Putting Tensors On and Off the GPU





In [586]:
# The reason we want our tensors/models on the GPU is
# because
# using a GPU results in faster computations



In [587]:
# Create a tensor (default on the CPU)

tensor=torch.tensor([1,2,3,4])

tensor,tensor.device



(tensor([1, 2, 3, 4]), device(type='cpu'))

In [588]:
# Move tensor to GPU

tensor_gpu=tensor.to(device)

tensor_gpu



tensor([1, 2, 3, 4])

In [589]:
# Moving tensor back to CPU

# If tensor is on GPU ,can't transfer it to NumPy

# tensor_gpu.numpy()

#TypeError: can't convert cuda:0 device type tensor
#to numpy. Use Tensor.cpu() to copy the tensor to host
#memory first.


In [590]:
# To fix the GPU tensor with Numpy issue,
# we can first set it to the CPU

tensor_gpu_to_cpu=tensor_gpu.cpu().numpy()
tensor_gpu_to_cpu

array([1, 2, 3, 4])