# Tensor - Basic Part - 1


In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.4.0+cu121'

In [3]:

"""
Tensor:-

A tensor is a multidimensional matrix containing elements
of a single data type.

"""



'\nTensor:-\n\nA tensor is a multidimensional matrix containing elements\nof a single data type.\n\n'

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [7]:
#convert numpy array to tensor

x=torch.from_numpy(arr)
x


tensor([1, 2, 3, 4, 5])

In [8]:
type(torch.from_numpy(arr))

torch.Tensor

In [9]:
x.dtype

torch.int64

In [10]:
torch.as_tensor(arr)


tensor([1, 2, 3, 4, 5])

In [11]:
# 2D numpy array

arr2d=np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
arr2d=arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [13]:
x2=torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
x

tensor([1, 2, 3, 4, 5])

In [16]:
arr[0]=99
arr

array([99,  2,  3,  4,  5])

In [17]:
x

tensor([99,  2,  3,  4,  5])

In [18]:
# So numpy creates a link between an array and tensor

# but we may not want sometimes.

# we want Numpy array to be manipulated but not affecting
# tensor

# so we need to do copy to avoid this.

# we can use .tensor to create a copy of Numpy array



In [19]:
arr_1=np.arange(0,10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_tns=torch.tensor(arr_1)
my_tns

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tns_1=torch.from_numpy(arr_1)
my_tns_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr_1[0]=88
arr_1


array([88,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [23]:
my_tns

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_tns_1

tensor([88,  1,  2,  3,  4,  5,  6,  7,  8,  9])

# Tensor Basic Part - 2

In [24]:
"""

How to create tensors from scratch completely using PyTorch

"""

In [25]:
new_arr= np.array([1,2,3])
new_arr

array([1, 2, 3])

In [26]:
new_arr.dtype

dtype('int64')

In [27]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [32]:
my_tensor=torch.Tensor(new_arr)
my_tensor

# Tensor is used for float data type

tensor([1., 2., 3.])

In [31]:
my_tensor.dtype

torch.float32

In [24]:
"""
 Instead of creating tensor from  numpy array create tensor
 from scratch.

"""

In [33]:
torch.empty(2,2)

tensor([[5.3386e-02, 3.2317e-41],
        [4.8729e-02, 3.2317e-41]])

In [35]:
torch.zeros(4,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [36]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [37]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [40]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [41]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [42]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [43]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [44]:
my_tensor=torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

In [45]:
my_tensor.dtype

torch.int64

In [47]:
my_tensor.type(torch.int32)

#change datatype of tensor

tensor([1, 2, 3], dtype=torch.int32)

In [48]:
my_tensor=my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [51]:
#creating tensor from random numbers

torch.rand(4,3)

tensor([[0.4893, 0.6659, 0.3641],
        [0.0376, 0.0157, 0.4984],
        [0.9364, 0.6153, 0.4478],
        [0.1296, 0.6368, 0.6718]])

In [52]:
torch.rand(10)

tensor([0.7121, 0.1457, 0.8803, 0.3070, 0.9236, 0.5035, 0.9479, 0.6048, 0.6082,
        0.1862])

In [53]:
torch.randn(10)

tensor([-1.0302, -1.1807, -0.5092,  0.6269, -1.1730,  0.4396,  0.9432,  0.5805,
         0.5660,  0.8144])

In [54]:
torch.randn(4,3)

tensor([[ 0.3053, -1.8745, -1.5145],
        [-1.2919,  2.3468, -0.9237],
        [ 0.8932,  2.1690, -0.0960],
        [ 1.3942, -0.7468, -1.1209]])

In [59]:
torch.randint(low=0,high=10,size=(5,5))

# low inclusive and high exclusive

tensor([[3, 4, 4, 4, 7],
        [9, 6, 5, 7, 8],
        [9, 7, 1, 6, 3],
        [0, 6, 5, 0, 1],
        [9, 9, 6, 1, 7]])

In [61]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [62]:
x.shape

torch.Size([2, 5])

In [64]:
torch.rand_like(x)
# will take shape of x

tensor([[0.8282, 0.2381, 0.7293, 0.2195, 0.0650],
        [0.9774, 0.4399, 0.0744, 0.8893, 0.7336]])

In [65]:
torch.randn_like(x)

tensor([[-0.9148, -1.0376, -2.3493, -1.0247, -1.7217],
        [-0.9726,  0.8629, -0.1559,  1.2791, -0.3862]])

In [67]:
torch.randint_like(x,low=0,high=10)

tensor([[0., 5., 4., 2., 5.],
        [5., 0., 2., 2., 4.]])

In [70]:
torch.manual_seed(42)

torch.rand(2,3)

#torch. rand should be in same cell with manual_seed

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])